import { assets } from './assets'
import type { TemplatePage } from './types'

export const page: TemplatePage = {
  meta: {
    title: 'Aurelia Estates | Private Residential Advisory',
    description: 'A premium real-estate website for US, UK, and international buyers seeking private viewings and residential advisory.',
    sourceUrl: 'https://example.com/aurelia-estates',
  },
  hero: {
    eyebrow: 'Private residential advisory for US and UK buyers',
    title: 'Aurelia Estates',
    subtitle:
      'Find the right home before the market finds you. Our advisors help serious movers, relocators, and investors compare refined residences from first brief to private viewing.',
    primaryCta: { label: 'Enquire Now', href: '#callback' },
    secondaryCta: { label: 'View Featured Homes', href: '#properties' },
    imageUrl: assets.heroImageUrl,
    highlights: ['US and UK buyer guidance', 'Private viewings arranged', 'Offer and due-diligence support'],
  },
  stats: [
    { value: 'USD 1.2M+', label: 'Typical US search brief', caption: 'City apartments, family homes, and second residences', icon: 'key' },
    { value: 'GBP 950K+', label: 'Typical UK search brief', caption: 'London, country houses, and regional relocation', icon: 'home' },
    { value: '24-48 hrs', label: 'Shortlist response', caption: 'Property matches prepared around your viewing window', icon: 'calendar' },
    { value: 'End-to-end', label: 'Advisory support', caption: 'Finance, legal, survey, and relocation introductions', icon: 'shield' },
  ],
  propertyTypes: {
    eyebrow: 'Start with the right brief',
    title: 'Homes matched to how people actually move',
    description: 'Choose the buying path that fits your life stage, market, and timeline, then request a tailored viewing plan.',
    items: [
      {
        title: 'Primary Residences',
        price: 'For families and long-term owners',
        description: 'Quiet neighbourhoods, school catchments, transport links, and homes that work beyond the first viewing.',
        imageUrl: assets.propertyTypes.apartments,
      },
      {
        title: 'Relocation Homes',
        price: 'For US, UK, and returning expat moves',
        description: 'Shortlists built around visa timing, commute needs, furnishings, and first-month practicalities.',
        imageUrl: assets.propertyTypes.villas,
      },
      {
        title: 'Investment Residences',
        price: 'For buy-to-let and portfolio buyers',
        description: 'Rental demand, operating costs, service charges, and exit strategy considered before enquiry.',
        imageUrl: assets.propertyTypes.hotelApartments,
      },
      {
        title: 'Second Homes',
        price: 'For seasonal and lifestyle ownership',
        description: 'Low-maintenance homes with privacy, security, local services, and flexible viewing support.',
        imageUrl: assets.propertyTypes.luxuryApartments,
      },
    ],
  },
  why: {
    eyebrow: 'About us',
    title: 'Residential advisors for thoughtful international buyers',
    description:
      'Aurelia Estates is built for buyers who want clarity before they commit. We combine local market knowledge with a calm advisory process, helping clients compare homes, understand trade-offs, and arrange private viewings with confidence.',
    imageUrl: assets.legacyImageUrl,
    stats: [
      { value: '12+ yrs', label: 'Residential advisory experience' },
      { value: 'US & UK', label: 'Buyer briefing expertise' },
      { value: 'Private', label: 'Discreet viewings and seller contact' },
      { value: 'Verified', label: 'Documents and next steps reviewed' },
    ],
  },
  properties: {
    eyebrow: 'Featured homes',
    title: 'Selected residences ready for private enquiry',
    description:
      'These sample listings are written as property briefs: location, guide price, living details, and a direct viewing request.',
    items: [
      {
        title: 'Aurelia Garden House',
        location: 'Cotswolds, United Kingdom',
        price: 'Guide price GBP 1.85M',
        summary: 'Detached stone residence with open-plan kitchen, south-facing garden, and guest suite above a quiet village lane.',
        beds: '4 beds',
        baths: '3 baths',
        size: '3,180 sq ft',
        badge: 'Country Home',
        imageUrl: assets.properties.waterfront,
        ctaLabel: 'Request a Viewing',
      },
      {
        title: 'Brookside Townhome',
        location: 'Brooklyn Heights, New York',
        price: 'Guide price USD 2.4M',
        summary: 'Renovated townhouse-style residence with private terrace, flexible office, and easy access to waterfront parks.',
        beds: '3 beds',
        baths: '2.5 baths',
        size: '2,260 sq ft',
        badge: 'City Living',
        imageUrl: assets.properties.island,
        ctaLabel: 'Arrange a Tour',
      },
      {
        title: 'Kensington Mews Apartment',
        location: 'London, United Kingdom',
        price: 'Guide price GBP 1.15M',
        summary: 'Elegant two-bedroom apartment with lift access, secure entry, and a calm mews setting close to museums.',
        beds: '2 beds',
        baths: '2 baths',
        size: '1,040 sq ft',
        badge: 'London Base',
        imageUrl: assets.properties.park,
        ctaLabel: 'Ask for Details',
      },
      {
        title: 'Pacific View Residence',
        location: 'Marin County, California',
        price: 'Guide price USD 3.2M',
        summary: 'Light-filled hillside home with layered terraces, office studio, and west-facing views over protected landscape.',
        beds: '4 beds',
        baths: '4 baths',
        size: '3,650 sq ft',
        badge: 'View Home',
        imageUrl: assets.properties.skyline,
        ctaLabel: 'Request a Viewing',
      },
      {
        title: 'Surrey Downs House',
        location: 'Surrey, United Kingdom',
        price: 'Guide price GBP 2.1M',
        summary: 'Family residence with generous reception rooms, garden office, and strong commuter links into central London.',
        beds: '5 beds',
        baths: '4 baths',
        size: '4,120 sq ft',
        badge: 'Family Brief',
        imageUrl: assets.properties.golf,
        ctaLabel: 'Arrange a Tour',
      },
      {
        title: 'Hudson Loft Residence',
        location: 'Tribeca, New York',
        price: 'Guide price USD 1.8M',
        summary: 'Loft-style apartment with broad windows, chef-ready kitchen, and concierge-managed building services.',
        beds: '2 beds',
        baths: '2 baths',
        size: '1,520 sq ft',
        badge: 'Investor Fit',
        imageUrl: assets.properties.lagoon,
        ctaLabel: 'Ask for Details',
      },
    ],
  },
  virtualTour: {
    eyebrow: 'Live property tour',
    title: 'Explore room-by-room with photo hotspots and live views',
    description:
      'A 3DVista-inspired live-view section lets buyers move between rooms, switch daylight mood, and inspect detail hotspots before arranging a private tour.',
    mediaFeatures: [
      'Room thumbnails update the main view instantly.',
      'Live day and evening views show how the home feels across the day.',
      'Clickable hotspots explain finishes, storage, appliances, and viewing next steps.',
      'Advisor-ready media notes keep the enquiry focused on what buyers need to verify.',
    ],
    nodes: [
      {
        id: 'living-room',
        name: 'Living Lounge',
        caption: 'Living Lounge | Daylight reception room',
        description: 'A generous reception space with natural light, layered seating, and clear flow into dining and entertaining zones.',
        thumbnailUrl: '/images/tour-live/living-day.jpg',
        liveViews: [
          { label: 'Day view', imageUrl: '/images/tour-live/living-day.jpg', tone: 'day' },
          { label: 'Evening ambience', imageUrl: '/images/tour-live/detail-lounge.jpg', tone: 'evening' },
        ],
        details: ['Open-plan reception', 'Layered lighting', 'Statement finishes', 'Space for formal dining'],
        hotspots: [
          {
            id: 'living-seating',
            label: 'Seating layout',
            description: 'Scaled for relaxed entertaining, with enough clearance for everyday circulation and view lines.',
            x: '48%',
            y: '60%',
          },
          {
            id: 'living-lighting',
            label: 'Feature lighting',
            description: 'Layered ceiling and pendant lighting gives the room a premium evening feel.',
            x: '50%',
            y: '21%',
          },
          {
            id: 'living-kitchen-link',
            label: 'Kitchen connection',
            description: 'Move into the kitchen to review appliance placement, worktop space, and breakfast seating.',
            x: '78%',
            y: '49%',
            targetId: 'kitchen',
          },
        ],
      },
      {
        id: 'kitchen',
        name: 'Kitchen',
        caption: 'Kitchen | Integrated appliances and breakfast island',
        description: 'A bright kitchen with island prep space, integrated appliances, and easy connection to informal dining.',
        thumbnailUrl: '/images/tour-live/kitchen-day.jpg',
        liveViews: [
          { label: 'Day view', imageUrl: '/images/tour-live/kitchen-day.jpg', tone: 'day' },
          { label: 'Evening ambience', imageUrl: '/images/tour-live/unsplash-living.jpg', tone: 'evening' },
        ],
        details: ['Central island', 'Integrated appliances', 'Garden-facing prep area', 'Dining connection'],
        hotspots: [
          {
            id: 'kitchen-island',
            label: 'Island workspace',
            description: 'Large stone island suitable for prep, serving, and informal buyer viewings around the room.',
            x: '48%',
            y: '57%',
          },
          {
            id: 'kitchen-appliances',
            label: 'Appliance wall',
            description: 'Integrated appliance stack keeps the working kitchen tidy and easy to maintain.',
            x: '73%',
            y: '45%',
          },
          {
            id: 'kitchen-suite-link',
            label: 'Primary suite',
            description: 'Continue into the private wing to compare bedroom proportions and storage.',
            x: '18%',
            y: '55%',
            targetId: 'bedroom',
          },
        ],
      },
      {
        id: 'bedroom',
        name: 'Primary Suite',
        caption: 'Bedroom Suite | Quiet private wing',
        description: 'A calm private suite with soft lighting, wardrobe access, and enough space for seating or a morning routine.',
        thumbnailUrl: '/images/tour-live/bedroom-day.jpg',
        liveViews: [
          { label: 'Day view', imageUrl: '/images/tour-live/bedroom-day.jpg', tone: 'day' },
          { label: 'Evening ambience', imageUrl: '/images/tour-live/bedroom-evening.jpg', tone: 'evening' },
        ],
        details: ['Private suite', 'Wardrobe access', 'Soft ceiling lighting', 'En-suite sightline'],
        hotspots: [
          {
            id: 'bedroom-lighting',
            label: 'Soft lighting',
            description: 'Recessed and decorative lighting supports a calm evening atmosphere.',
            x: '52%',
            y: '16%',
          },
          {
            id: 'bedroom-storage',
            label: 'Wardrobe access',
            description: 'Storage and dressing access are visible from the main room, useful for relocation buyers.',
            x: '76%',
            y: '48%',
          },
          {
            id: 'bedroom-lounge-link',
            label: 'Back to lounge',
            description: 'Return to the reception space to compare guest flow and entertaining layout.',
            x: '24%',
            y: '58%',
            targetId: 'living-room',
          },
        ],
      },
    ],
  },
  payment: {
    eyebrow: 'Buyer journey',
    title: 'A calmer path from first enquiry to final offer',
    description:
      'Aurelia turns a broad search into a focused plan: clarify the brief, compare suitable homes, then move into viewings with the right documents and advisors ready.',
    imageUrl: assets.paymentImageUrl,
    accepted: ['Brief and budget review', 'Curated viewing shortlist', 'Offer and due-diligence support'],
  },
  offices: {
    eyebrow: 'Advisory desks',
    title: 'Speak with a specialist in your market',
    description: 'Connect with the right advisor for London, New York, countryside relocation, or cross-border purchase planning.',
    items: [
      { title: 'London Advisory Desk', description: 'Prime London, commuter towns, and UK relocation support.', imageUrl: assets.offices.happiness },
      { title: 'New York Advisory Desk', description: 'Manhattan, Brooklyn, and investor-ready city residences.', imageUrl: assets.offices.city },
      { title: 'Country Homes Desk', description: 'Village, estate, and second-home searches across the UK.', imageUrl: assets.offices.hills },
      { title: 'West Coast Desk', description: 'California lifestyle homes, family moves, and view-led residences.', imageUrl: assets.offices.towers },
    ],
  },
  leadForm: {
    title: 'Enquire about a property',
    description: 'Share your preferred market, budget, and timing. An advisor will respond with suitable next steps.',
    submitLabel: 'Send Enquiry',
    successMessage: 'Details saved. We will reach you shortly.',
    fields: [
      { name: 'name', label: 'Name', placeholder: 'Full name', type: 'text', requiredMessage: 'Name is required.' },
      { name: 'email', label: 'Email', placeholder: 'you@example.com', type: 'email', requiredMessage: 'Enter a valid email.' },
      { name: 'phone', label: 'Phone', placeholder: '+1 or +44 phone number', type: 'tel', requiredMessage: 'Phone is required.' },
      {
        name: 'interest',
        label: 'Interest',
        placeholder: 'Select interest',
        type: 'select',
        requiredMessage: 'Select an interest.',
        options: ['Primary residence', 'Relocation', 'Investment property', 'Second home', 'Private viewing'],
      },
      {
        name: 'message',
        label: 'Message',
        placeholder: 'Budget, bedrooms, preferred location, or viewing timeline',
        type: 'textarea',
        requiredMessage: 'Message is required.',
      },
    ],
  },
}
